### ISSUE TITLE
Not scrolling to the right position!

### ISSUE THREAD

**Issue by thushan95** [Amzd/ScrollViewProxy#14]
When enabled text modifiers on the button body, scrollTo function not working properly. It's scrolling random positions. Looking for a solution. Thanks.

https://user-images.githubusercontent.com/69820290/118195838-a6957f80-b454-11eb-874b-a63a37448c0f.mp4

**Comment by Amzd** [comment]
Haha that's so strange.

I think what's happening is SwiftUI reloads the view because you use currentCategory in the body. Then ScrollViewReader tries to get the view to scroll to but it's being created so the position is incorrect? maybe?

Anyway, you could try to wrap the scrollTo in a DispatchQueue.main.async (or maybe even two?) and see if that works. In theory then the scrollTo function should run when SwiftUI is done reloading views.

**Comment by thushan95** [comment]
Yes, something strange is happening. 
But, it's not resolved yet. I tried as you said with DispatchQueue.main.async and 2 wraps as well. Also, I tried with asyncAfter with a deadline delay.😐

**Comment by Amzd** [comment]
If you can create a small isolated example view that I can debug that would be great.

**Comment by thushan95** [comment]
[ScrollViewProxyTest.zip](https://github.com/Amzd/ScrollViewProxy/files/6485829/ScrollViewProxyTest.zip)
Yes, sure. I created a sample project and attached it.

**Comment by Amzd** [comment]
Ah, I see what's going on. 

When I answered your other question on how to fix which scrollview it selects I asked you to put the reader around the scrollview but that actually doesn't work. I will add that in the README because that's a big difference between my and Apples implementation that I didn't realize existed.

You can simply fix this bug by moving the ScrollViewReader *inside* the ScrollView. 

To fix the #13 we need to look at the `introspectScrollView` which I think returns the wrong scroll view
